// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Data;

#nullable disable

namespace Task.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814164835_ProductSeedData")]
    partial class ProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ergonomic wireless mouse with USB receiver",
                            Name = "Wireless Mouse",
                            Price = 15.99m,
                            rate = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "RGB backlit mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 49.99m,
                            rate = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "7-in-1 USB-C hub with HDMI and card reader",
                            Name = "USB-C Hub",
                            Price = 29.50m,
                            rate = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Adjustable aluminum laptop stand",
                            Name = "Laptop Stand",
                            Price = 22.00m,
                            rate = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Full HD webcam with built-in microphone",
                            Name = "Webcam 1080p",
                            Price = 34.99m,
                            rate = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
